### ISSUE TITLE
No validation on required

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/wysiwyg-field_type#13]
When the field type is required there is no js validation (the form doesn't submit and no messages)

**Comment by RyanThompson** [comment]
Ok - this one should be pretty simple to fix - the textarea has HTML required on it pry.

**Comment by j-hubb** [comment]
Getting An invalid form control with name='entry_content' is not focusable. in console

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/bc9bdf65312a0382e0cf4ecb1dfb20afa98188cc

**Comment by RyanThompson** [comment]
Try er now

**Comment by j-hubb** [comment]
No, still not working

**Comment by j-hubb** [comment]
Strange thing is, it's working with js disabled

**Comment by j-hubb** [comment]
http://share.jhubb.io/59E0H1t

**Comment by RyanThompson** [comment]
Keep debug mode on when testing - so your twig views stay refreshed. I removed the required attribute there and will just let the validator handle it.

**Comment by j-hubb** [comment]
Oops,

Still getting An invalid form control with name='entry_content' is not focusable.

**Comment by RyanThompson** [comment]
Composer update - does your textarea still show required in the markup?

**Comment by j-hubb** [comment]
Nothing to install or update (already done)

<textarea name="entry_content" data-field="entry_content" data-disk="" data-height="400" placeholder="" data-folders="" data-locale="en" data-buttons="html,formatting,bold,italic,deleted,unorderedlist,orderedlist,outdent,indent,link,alignment,horizontalrule,underline" data-plugins="table,video,fontsize,filemanager,imagemanager,fullscreen" data-field_name="entry_content" data-provides="anomaly.field_type.wysiwyg" required="" dir="ltr" style="display: none;">&lt;p&gt;Testing&lt;/p&gt;</textarea>

**Comment by j-hubb** [comment]
`<textarea name="entry_content" data-field="entry_content" data-disk="" data-height="400" placeholder="" data-folders="" data-locale="en" data-buttons="html,formatting,bold,italic,deleted,unorderedlist,orderedlist,outdent,indent,link,alignment,horizontalrule,underline" data-plugins="table,video,fontsize,filemanager,imagemanager,fullscreen" data-field_name="entry_content" data-provides="anomaly.field_type.wysiwyg" required="" dir="ltr" style="display: none;">&lt;p&gt;Testing&lt;/p&gt;</textarea>`

**Comment by RyanThompson** [comment]
Make sure you composer update and run `php artisan twig:clean`
