### ISSUE TITLE
Hard coded paths in JS render 404 for file manager

### ISSUE THREAD

**Issue by bhannah** [anomalylabs/wysiwyg-field_type#15]
Lines 33 and 44 in /resources/js/plugins/file_manager.js have URL's hard coded to call the file upload and file browser popup.  If not installed on the web root, this renders a 404.    

My install of PyroCMS is served at http://localhost/PyroTest/pyrocms/public/   but the calls to the file manager is requesting  http://localhost/streams/wysiwyg-field_type/index?mode=image&folders%5B%5D=

**Comment by bhannah** [comment]
Actually, changing those values don't affect anything.

**Comment by RyanThompson** [comment]
Can you try prefixing it with `APPLICATION_URL`

**Comment by RyanThompson** [comment]
I think this will do it: https://github.com/anomalylabs/wysiwyg-field_type/commit/8bd170de22d89e604e3cb845d923a95cb8f36b0c

**Comment by RyanThompson** [comment]
Let me know if that doesn't work. You might need to use a qualified domain like foo.local or something though.

**Comment by bhannah** [comment]
Yes, that worked fine.  I was actually looking in the wrong file.  I was working with images and didn't realize there was an imagemanager.js separate from filemanager.js.   I've update both with APPLICATION_URL +  and both are working well, now.   Thanks!

**Comment by RyanThompson** [comment]
Sure thing! I’ve tagged an update for both as well so a composer update will do it for ya.
