### ISSUE TITLE
the data never shows but gets saved

### ISSUE THREAD

**Issue by jaapjolman** [anomalylabs/wysiwyg-field_type#3]
the data never shows on the edit page but it is stored in the database

**Comment by RyanThompson** [comment]
Are you running into a JS error or anything like that? Can you 777 your storage directory and try again?

**Comment by sebastiaanluca** [comment]
Same problem here. Doesn't show in the back-end and can't get it to show in the front-end either. So that's definitely a bug.

Additionally, what should I put in the front-end Twig template to make it show? Tried the following without result:

```
{{ entry.content.rendered|raw }}
{{ entry.fields.content.rendered|raw }}
{{ page.fields.content.rendered|raw }}
{{ page.content.rendered|raw }}
{{ page.content.text|raw }}
{{ entry.content.text|raw }}
{{ content.text|raw }}
{{ content }}
```
